export enum ROLESAUTH {
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  ONEEMPLOYEE = 'ONEEMPLOYEE',
  SALEOWNER = 'SALEOWNER',
  GAMEOWNER = 'GAMEOWNER',
  TICKETEMPLOYEE = 'TICKETEMPLOYEE',
  SALEEMPLOYEE = 'SALEEMPLOYEE',
}

export enum ROLES {
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  CLIENT = 'CLIENT',
}
